spring.application.name=biovectorbot

bot.token=${BIO_BOT_TOKEN}
deekseek.api.key=${DEEPSEEK_API_KEY}
deepseek.url=https://api.deepseek.com/chat/completions


#spring.autoconfigure.exclude=\
#  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration 
  
spring.datasource.url=jdbc:mysql://localhost:3306/biovector_db
spring.datasource.username=root
spring.datasource.password=${MYSQL_DS_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
